spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:${port}/${db}?createDatabaseIfNotExist=true
    username: ${user}
    password: ${password}
